### ISSUE TITLE
About the pinMode on analogPin

### ISSUE THREAD

**Issue by ChengRui24** [ggzucco/LM35#1]
Thanks for providing this useful package!
but I have a little question about the analogPin.
I saw you and other coder set A0 with OUTPUT,  before analogRead(A0).
For what I know, this A0 is receive the data from lM35, it should be INPUT mode.

And the page about AnalogInputPins on arduino.cc is writting:
> The analogRead command will not work correctly if a pin has been previously set to an output, so if this is the case, set it back to an input before using analogRead.  

I am new for learning Andruino, so I don't know a lof about this stuff, i can't figure out why, and I can't search out any answer.

thanks again

**Comment by ggzucco** [comment]
Sorry to be late

I think taht the corretly use for this sensor is setting as an Input

I add a document read me with sample of code about how to use
